spring:
#   base de datos posta    
    datasource:
        url: jdbc:mysql://localhost/politics
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        open-in-view: false
        show-sql: true
        hibernate:
            format_sql: true
            ddl-auto: create-drop


flyway:
   url: jdbc:mysql://localhost/politics
   schemas: politics
   user: root
   password: root
   locations: classpath:dbasdasd/migration
